image: docker:stable

stages:
  - test

before_script:
  - docker info

after_script:
  - docker rm -f $TERRAFORM_CONTAINER_NAME || true

Run test:
  stage: test
  script:
    - echo "Pull REST API workflow"
    - docker pull $REST_API_IMG
    - docker run -d -e BAM_IP=$BAM_IP --name $TERRAFORM_CONTAINER_NAME $REST_API_IMG
    - echo "Install Golang"
    - docker exec --user root $TERRAFORM_CONTAINER_NAME sh -c "apt-get update && apt-get install -y wget unzip build-essential && rm -rf /var/lib/apt/lists/*"
    - docker exec --user root $TERRAFORM_CONTAINER_NAME sh -c "wget --quiet https://golang.org/dl/go1.14.9.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.14.9.linux-amd64.tar.gz && rm go1.14.9.linux-amd64.tar.gz"
    - echo "Install Terraform"
    - docker exec --user root $TERRAFORM_CONTAINER_NAME sh -c "wget --quiet https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip && unzip terraform_0.13.1_linux_amd64.zip && mv terraform /usr/bin && rm terraform_0.13.1_linux_amd64.zip"
    - echo "Copy source code"
    - docker cp . $TERRAFORM_CONTAINER_NAME:/terraform
    - echo "Run Acceptance Tests"
    - docker exec --user root $TERRAFORM_CONTAINER_NAME sh -c "cd /terraform && export PATH=$PATH:/usr/local/go/bin && export TF_ACC=true && go test ./test/ -v"
