language: go

go:
  - 1.x

script:
  - echo "Build Terraform Provider Bluecat for Windows"
  - env GOOS=windows GOARCH=amd64 go build -o terraform-provider-bluecat-window-amd64
  - echo "Build Terraform Provider Bluecat for Linux"
  - env GOOS=linux GOARCH=amd64 go build -o terraform-provider-bluecat-linux-amd64
  - echo "Build Terraform Provider Bluecat for Mac"
  - env GOOS=darwin GOARCH=amd64 go build -o terraform-provider-bluecat-mac-amd64

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  skip_cleanup: true
  on:
    tags: true
